
#TODO: auto add virtual functions

help(){
  echo "Usage: $0 [-name Name] [-template Template] [-Ddef1 -Ddef2 ...] [-Iinc1 -I inc2 ...] header_files"
  echo "Or $0 [--name=Name] [--template=Template] header_files"
  echo 'If header files contains at least 2 files, they will be merged into 1 file ${Name}.h'
  exit 0
}

ARGV=$@
HEADERS=()
ARGV2=()
while [ $# -gt 0 ]; do
  VAR=
  case "$1" in
  -I|-L|-l) # -I inc
    ARGV2+=($1)
    shift
    ARGV2+=($1)
   ;;
  -D*|-I*|-L*|-l*) # -Iinc
    ARGV2+=($1)
    ;;
  --*=*)
    ARGV2+=($1)
    PAIR=${1##--}
    VAR=${PAIRE%=*}
    VAL=${PAIR##*=}
    ;;
  -*)
    ARGV2+=($1)
    VAR=${1##-}
    shift
    ARGV2+=($1)
    VAL=$1
    ;;
  *)
    HEADERS+=(${1})
    #break
    ;;
  esac
  if [ -n "$VAR" ]; then
    VAR_U=`echo $VAR | tr "[:lower:]" "[:upper:]"`
    echo "$VAR_U"
    eval $VAR_U=$VAL
  fi
  shift
done

[ -n "$NAME" ] || help
[ -n "$TEMPLATE" ] || TEMPLATE=capi
echo "name: $NAME, template: $TEMPLATE"

HEADER=${HEADERS[0]}
if [ ${#HEADERS[@]} -gt 1 ]; then
  HEADER=/tmp/${NAME}.h
  echo "cat ${HEADERS[@]} > $HEADER"
  cat ${HEADERS[@]} > $HEADER
fi
echo "./mkapi ${ARGV2[@]} $HEADER >/dev/null"
[ -e mkapi ] || {
  echo "build mkapi first (run make. need clang3.4 sdk)"
  exit 0
}
./mkapi ${ARGV2[@]} $HEADER >/dev/null

NAME_U=`echo $NAME | tr "[:lower:]" "[:upper:]"`
NAME_L=`echo $NAME | tr "[:upper:]" "[:lower:]"`
YEAR=`date +%Y`

mkdir -p /tmp/mkapi
mv ${NAME}_declarations /tmp/mkapi/declarations
mv ${NAME}_resolvers /tmp/mkapi/resolvers
mv ${NAME}_definitions /tmp/mkapi/definitions

#TODO: author info
echo "generating ${NAME}_api.h..."
# TODO: find config/name/template.{h,cpp} first
#cat $COPY | sed "s/%YEAR%/$YEAR/g" > ${CLASS}.h
if [ -f config/${NAME}/include ]; then
  cp -af config/${NAME}/include /tmp/mkapi
  cat template/${TEMPLATE}/name_api.h |sed -n '/#include "%Name%\.h"/!p;/#include "%Name%\.h"/r/tmp/mkapi/include' \
  > /tmp/mkapi/name_api.h
else
  cp -af template/${TEMPLATE}/name_api.h /tmp/mkapi
fi
cat /tmp/mkapi/name_api.h |sed "s/%Name%/$NAME/g" | sed "s/%NAME%/$NAME_U/g"  | sed "s/%name%/$NAME_L/g" \
    |sed "s,%TEMPLATE%,$TEMPLATE,g" \
    |sed -n '/%Declare%/!p;/%Declare%/r/tmp/mkapi/declarations' \
    >${NAME}_api.h

echo "generating ${NAME}_api.cpp..."
cp -af template/${TEMPLATE}/name_api.cpp /tmp/name_api.cpp.in
cp -af template/${TEMPLATE}/name_api.cpp /tmp/mkapi
if [ -f config/${NAME}/version ]; then
  cp -af config/${NAME}/version /tmp/mkapi
  cat /tmp/name_api.cpp.in |sed 's,CAPI_HAS_%NAME%_VERSION,1,g' |sed -n '/%VERSIONS%/!p;/%VERSIONS%/r/tmp/mkapi/version' \
  > /tmp/mkapi/name_api.cpp
  cp -af /tmp/mkapi/name_api.cpp /tmp/name_api.cpp.in
fi
if [ -f config/${NAME}/lib ]; then
  cp -af config/${NAME}/lib /tmp/mkapi
  cat /tmp/name_api.cpp.in |sed -n '/%LIBS%/!p;/%LIBS%/r/tmp/mkapi/lib' \
  > /tmp/mkapi/name_api.cpp
  cp -af /tmp/mkapi/name_api.cpp /tmp/name_api.cpp.in
fi
if [ -f config/${NAME}/dso ]; then
  cp -af config/${NAME}/dso /tmp/mkapi
  cat /tmp/name_api.cpp.in |sed -n '/%DSO%/!p;/%DSO%/r/tmp/mkapi/dso' \
  > /tmp/mkapi/name_api.cpp
  cp -af /tmp/mkapi/name_api.cpp /tmp/name_api.cpp.in
fi

[ -f config/${NAME}/skip ] && SKIP_REG=`cat config/${NAME}/skip |xargs |tr ' ' '|'`
cat /tmp/mkapi/name_api.cpp |sed "s/%Name%/$NAME/g" | sed "s/%NAME%/$NAME_U/g"  | sed "s/%name%/$NAME_L/g" \
    |sed "s,%TEMPLATE%,$TEMPLATE,g" \
    |sed -n '/%DEFINE_RESOLVER%/!p;/%DEFINE_RESOLVER%/r/tmp/mkapi/resolvers' \
    |sed -n '/%DEFINE%/!p;/%DEFINE%/r/tmp/mkapi/definitions' \
     >/tmp/${NAME}_api.cpp

test -n "$SKIP_REG" && sed -E "/$SKIP_REG/s/^/\/\//" /tmp/${NAME}_api.cpp > ${NAME}_api.cpp || mv {/tmp/,}${NAME}_api.cpp
FOOTER="//this file is generated by \"mkapi.sh $ARGV\"" 
echo $FOOTER >> ${NAME}_api.h
echo $FOOTER >> ${NAME}_api.cpp

